export interface IResponse {
  config: object;
  data: IResponseData;
  headers: object;
  request: any;
  status: number;
  statusText: string;
}

export interface IResponseData {
  page: number;
  results: IResponseResult[];
  total_pages: number;
  total_results: number;
}

export interface IResponseResult {
  backdrop_path?: string;
  first_air_date: string;
  genre_ids: number[];
  title: string;
  id: number;
  name: string;
  origin_country: string[];
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path: string;
  vote_average: number;
  vote_count: number;
}

export enum CATEGORIES {
  TRENDING = "Trending Now",
  TOP = "Top Rated",
  ACTION = "Action Movies",
  COMEDY = "Comedy Movies",
  HORROR = "Horror Movies",
  ROMANCE = "Romance Movies",
  DOCUMENTARIES = "Documentaries",
}

// Generated by https://quicktype.io

export interface IVideoResult {
  id: string;
  iso_639_1?: string;
  iso_3166_1?: string;
  key: string;
  name: string;
  site: string;
  size?: number;
  type: string;
}

export interface IVideoData {
  id: number;
  results: IVideoResult[];
}
